### ISSUE TITLE
how to cancel the playing alarm sound?

### ISSUE THREAD

**Issue by kingctan** [emekalites/react-native-alarm-notification#2]
how to cancel the playing alarm sound? 
can you please add one api to this feature?

Thanks.

**Comment by emekalites** [comment]
will work on that, thanks

**Comment by emekalites** [comment]
done in v1.1.0

**Comment by haifahrul** [comment]
@emekalites it's not working in Android 7.1.1
I'm tested with step :
1. Set Schedule
2. Close or Kill the App
3. When notif is fired, I dismiss the notif, but the sound still not stoping

**Comment by emekalites** [comment]
what android version are you testing on?

**Comment by bsdunx** [comment]
This does not seem to be working for me on 7.1 or 8.0, perhaps not on any version.

**Comment by haifahrul** [comment]
@bsdunx Did you have tested on 7.1 or 8.0 ?

**Comment by bsdunx** [comment]
7.1 via emulator and 8.1 on actual device.

**Comment by akinmac002** [comment]
The problem still persists. It no longer works in the solution I suggested previously. 

> @emekalites it's not working in Android 7.1.1 also Android above 7.1.1
> I'm tested with step :
> 
> 1. Set Schedule
> 2. Close or Kill the App
> 3. When notif is fired, I dismiss the notif, but the sound still not stop

I'm having this problem.

Android 7.1 - Sony Experia Z5 Compact

**Comment by akinmac002** [comment]
The problem still persists. It no longer works in the solution I suggested previously. @emekalites 

> @emekalites it's not working in Android 7.1.1 also Android above 7.1.1
> I'm tested with step :
> 
> 1. Set Schedule
> 2. Close or Kill the App
> 3. When notif is fired, I dismiss the notif, but the sound still not stop

I'm having this problem.

Android 7.1 - Sony Experia Z5 Compact

**Comment by ASIF-Mahmud1** [comment]
I am also facing the same issue

**Comment by sadia-onyxtec** [comment]
Any solution?

**Comment by josedomingos919** [comment]
Hello, @emekalites i have the same problem..
